# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:

    runs-on:  self-hosted

   
    steps:
      - name: pull then resources types repo
        run: |
          cd /home/azureuser/resource-types-website/_work/resource-types-website/resource-types-website/warehouse/resource-types
          git pull
      - name: docker build
        run: |
          cd /home/azureuser/resource-types-website/_work/resource-types-website/resource-types-website/warehouse
          sudo docker-compose build 
          sudo docker-compose down
          sudo docker-compose --env-file server.env up  -d